[project]
name = 'Decentralized-Specialized-Historic-Building-Restoration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.craftsperson-verification]
path = 'contracts/craftsperson-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-authentication]
path = 'contracts/material-authentication.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
